pipeline {
    agent any

    environment {
        // Name for the image being built and scanned
        APP_IMAGE = "local-app-build:${env.BUILD_NUMBER}"
    }

    triggers {
        githubPush()
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build App Image') {
            steps {
                // Build the user's application from the repo
                sh "docker build -t ${APP_IMAGE} ."
            }
        }

        stage('Security Audit') {
            steps {
                script {
                    sh """
                        mkdir -p reports

                        docker pull parthg23/security-auditor:latest

                        docker run --rm \
                        -v /var/run/docker.sock:/var/run/docker.sock \
                        -v ${WORKSPACE}/reports:/app \
                        -w /app \
                        parthg23/security-auditor:latest \
                        /audit/containertest.sh ${APP_IMAGE}
                    """
                }
            }
        }

        stage('Install Verification Tools') {
            steps {
                sh 'pip install cryptography --quiet --break-system-packages || pip install cryptography --quiet'
            }
        }

        stage('Verify Signature') {
            steps {
                script {
                    // This checks the signature against the sbom.json generated by your toolkit
                    def result = sh(
                        script: 'python3 verify_sig.py output.sig sbom.json public_key.pem',
                        returnStatus: true
                    )

                    if (result != 0) {
                        error("❌ Signature is INVALID or Audit Failed — build aborted.")
                    }
                }
            }
        }
    }

    post {
        success {
            echo "✅ Audit Passed & Signature is VALID."
            // Clean up the local image to save space
            sh "docker rmi ${APP_IMAGE}"
        }
        failure {
            echo "❌ Security Check FAILED."
        }
    }
}